POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZmVAZ21haWwuY29tIiwiaWF0IjoxNjYzMDc4MTU3LCJleHAiOjE2NjMxNjQ1NTd9.RYWd3EShb5ERV1Yvy5N9aWamRzg690danjeuHsJiveI

{"content": "coucouc c'est rereposté! "}
###
GET http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZmVAZ21haWwuY29tIiwiaWF0IjoxNjYyODEzMDk0LCJleHAiOjE2NjI4OTk0OTR9.aoxlRFWBSvktnPXqqf07fYqm_TMqIVP0XrwLg314Hew


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{"email": "fefe@gmail.com","password": "123456"}

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{"email": "fefe@gmail.com","password": "123456","confirmPassword": "123456"}

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{"email": "hadock@gmail.com","password": "123456","confirmPassword": "123456"}